version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    reviewers:
      - "Bluebird-Community/dependabot-reviewers-node"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
