---
name: Build Cortex Time Series Storage Plugin
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on:
      group: Default
      labels:
        - self-hosted
        - Linux
        - X64
    steps:
      - uses: actions/checkout@v4
      - name: Add workspace to git safe.directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Compile plugin from source
        run: |
          make
      - name: Execute Integration Test suite
        run: |
          make integration-tests
      - name: Publish Unit Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          check_name: Test Report
      - name: Persist KAR file
        uses: actions/upload-artifact@v4
        with:
          name: prom-tss-kar-file
          path: assembly/kar/target/opennms-cortex-tss-plugin.kar
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: prom-tss-kar-file
      - name: Generate KAR file checksum
        run: shasum -a 256 -b opennms-cortex-tss-plugin.kar > shasum256.txt
      - name: Create release archive
        run: tar czf opennms-cortex-tss-plugin.tar.gz opennms-cortex-tss-plugin.kar shasum256.txt
      - name: Generate tar.gz checksum
        run: shasum -a 256 -b opennms-cortex-tss-plugin.tar.gz > opennms-cortex-tss-plugin.sha256
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          make_latest: true
          generate_release_notes: true
          files: |
            *.tar.gz
            *.sha256
